# Generated by Django 3.2.6 on 2021-08-22 14:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='utils.base_model.uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utils.model_date.created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='utils.model_date.updated_at')),
                ('title', models.CharField(max_length=512, verbose_name='Наименование поста')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='utils.base_model.uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utils.model_date.created_at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='utils.model_date.updated_at')),
                ('like', models.CharField(choices=[('LIKE', 'LIKE'), ('DISLIKE', 'DISLIKE')], max_length=7, verbose_name='Like-Dislike')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'PostLike',
                'verbose_name_plural': 'PostsLikes',
            },
        ),
    ]
